<?php /** @var \YuriiZh\ControllerDemo\Block\Demo $block */
    $repositoryUrl = $block->escapeUrl($block->getRepositoryUrl());
?>
<div class="full-name"><?= $block->escapeHtml(__('Full name:')) ?>
    <?= $block->escapeHtml($block->getFullName()) ?>
</div>
<div class="repository-url">
    <?= $block->escapeHtml(__('Repository URL:')) ?>
    <a href="<?= $repositoryUrl ?>" target="_blank">
        <?= $repositoryUrl ?>
    </a>
</div>
